---
- name: Load OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- block:
  - name: Backup shorewall4/6 configuration in case it needs to be reverted
    shell: "tar -C /etc --ignore-failed-read -cf /tmp/shorewall_backup.tar shorewall shorewall6"
    args:
      warn: no
    changed_when: False
  - name: Install and configure shorewall4
    include_tasks: "shorewall4.yml"
    when: shorewall4 and shorewall4_package_state != 'absent'
  - name: Install and configure shorewall6
    include_tasks: "shorewall6.yml"
    when: shorewall6 and shorewall6_package_state != 'absent'
  rescue:
  - debug:
      msg: >
          Oops! Something went wrong, reverting shorewall4/6 configuration to previous state.
          Your previous config will be copied to {{ shorewall_backup_archive_path }} and the failed config to {{ shorewall_failed_archive_path }}
  - name: Make a copy of the failed configuration
    shell: "tar -C /etc --ignore-failed-read -cf {{ shorewall_failed_archive_path|quote }} shorewall shorewall6"
    args:
      warn: no
  - name: Restore configuration from backup
    command: "tar -C /etc -xf /tmp/shorewall_backup.tar"
    args:
      warn: no
  - name: Archive backed up configuration
    copy: src="/tmp/shorewall_backup.tar" dest="{{ shorewall_backup_archive_path }}" remote_src=yes backup=yes
  - name: Test old shorewall4 configuration
    shell: "shorewall check"
    changed_when: False
    when: shorewall4 and shorewall4_package_state != 'absent'
  - name: Test shorewall6 configuration
    shell: "shorewall6 check"
    changed_when: False
    when: shorewall6 and shorewall6_package_state != 'absent'
  always:
  - name: Remove temporary backup
    file:
      dest: "/tmp/shorewall_backup.tar"
      state: absent
    changed_when: False
  when: shorewall4 or shorewall6

# Uninstall
- name: Uninstall shorewall4 if requested
  include_tasks: "uninstall4.yml"
  # shorewall6 depends on shorewall4, so check that too
  when: shorewall4_package_state == 'absent' and not shorewall6_package_state != 'absent'
- name: Uninstall shorewall6 if requested
  include_tasks: "uninstall6.yml"
  when: shorewall6_package_state == 'absent'
