---
- name: Install shorewall4
  package:
    name: "{{ item }}"
    state: "{{ shorewall4_package_state }}"
  loop: "{{ shorewall4_packages }}"

- name: Check shorewall version
  shell: "shorewall version"
  register: __shorewall4_version
  check_mode: no
  changed_when: False
  failed_when: False

- name: Check shorewall4 version presence
  fail:
    msg: "Shorewall4 version could not be detected! (Possible error message: '{{ __shorewall4_version.stderr }}'"
  when: not __shorewall4_version.stdout_lines

- name: Set shorewall4 version facts
  set_fact:
    shorewall4_major_version: "{{ __shorewall4_version.stdout.split('.')[:2]|join('.') }}"
    shorewall4_full_version: "{{ __shorewall4_version.stdout.strip() }}"

- debug:
    msg: "shorewall4_major_version: {{ shorewall4_major_version }} shorewall4_full_version: {{ shorewall4_full_version }}"

- name: Check shorewall4 version
  fail:
    msg: "Shorewall version {{ shorewall4_major_version }} is not supported by this role, sorry! ({{ shorewall4_minimum_version }} or newer required)"
  when: shorewall4_major_version is version(shorewall4_minimum_version, '<')

- name: Configure shorewall4 main options
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/shorewall.conf.j2"
    dest: "/etc/shorewall/shorewall.conf"
    owner: "root"
    group: "root"
    mode: 0644
    # backup: yes
  notify: Restart shorewall4

- name: Configure shorewall4 params
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/params.j2"
    dest: "/etc/shorewall/params"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 zones
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/zones.j2"
    dest: "/etc/shorewall/zones"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 interfaces
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/interfaces.j2"
    dest: "/etc/shorewall/interfaces"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 policy
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/policy.j2"
    dest: "/etc/shorewall/policy"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 rules
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/rules.j2"
    dest: "/etc/shorewall/rules"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 blrules
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/blrules.j2"
    dest: "/etc/shorewall/blrules"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4

- name: Configure shorewall4 masq
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/masq.j2"
    dest: "/etc/shorewall/masq"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4
  when: shorewall4_full_version is version('5.2.0', '<')

- name: Configure shorewall4 snat
  template:
    src: "shorewall4/{{ shorewall4_major_version }}/snat.j2"
    dest: "/etc/shorewall/snat"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart shorewall4
  when: shorewall4_full_version is version('5.2.0', '>=')

- name: Test shorewall4 configuration
  command: "shorewall check"
  changed_when: False
